api = "v1"
name = "finki-plugin"

[event.timer]
interval = 15 # In seconds

[permission.task]
create = true

[permission.network]
urls = ["https://www.finki.ukim.mk/"]

[permission.storage]
max-size = 10240 # 10MB
